### ISSUE TITLE
Proteins have less peptides than before

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#1]
Some proteins have a lot less peptides mapping to them than before. Example: P08238 (Heat shock protein HSP 90-beta (HS90B_HUMAN)) used to have 32 peptides, now it only has 10...

(Tested by loading only the X! Tandem identifications of the example dataset.)

**Comment by dominik-kopczynski** [comment]
Something goes terribly wrong, when I launch two times the same analysis with exactly the same SG result file and parameter file in PS, I get sometimes 9 peptides for P08238, sometimes 10 peptides.

**Comment by hbarsnes** [comment]
Is this still an issue? I cannot seem to reproduce it with the current code?
