### ISSUE TITLE
Loading results from more than one search engine results in no validated hits

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#12]
Loading results from more than one search engine results in no validated hits.

Not sure of the underlying cause, but for the Spectrum IDs tab both inputMap.getAdvocateContribution(…) and inputMap.getAdvocateUniqueContribution(…) return 0.0 for all the search engines, so this could perhaps be one place to start the debugging?

**Comment by mvaudel** [comment]
Solved in https://github.com/compomics/peptide-shaker/commit/531b7622066d185d924483ae2042b4cba0d2983c
