### ISSUE TITLE
Confidence is identical for all spectrum id results in the Spectrum IDs tab

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#13]
The confidence for all spectrum id results in the Spectum IDs tab is zero when loading individual data from Comet, MS Amanda, MS-GF+, MyriMatch, Andromeda and Tide. For other algorithms it is always set to the same value, i.e. OMSSA to 32, Novor to 100, and X! Tandem to 52.

Maybe just a map issue as the PSM, peptide and protein confidences all seem to be fine?

On a related note, a null pointer now occurs when selecting spectra without any hits in the Spectrum IDs tab.

**Comment by mvaudel** [comment]
Solved.
https://github.com/compomics/peptide-shaker/commit/531b7622066d185d924483ae2042b4cba0d2983c
