### ISSUE TITLE
Validation status "No Validation" in the Spectrum IDs tab

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#14]
Validated status is set to Not Validated for all spectrum identification results in the Spectrum IDs tab.

Plus, the spectrum identification result table is not always sorted on the Confidence column.

**Comment by hbarsnes** [comment]
Maybe due to changes in the populateIdResultsTable method in the SpectrumIdentificationsPanel class?

Used to say "sort assumptions by tag or peptide -> confidence -> search engine -> peptide sequence" but now it says "sort peptides by score, tool, and sequence"?

And the scores are always zero?

**Comment by hbarsnes** [comment]
The orignal issue has been fixed, but there are still some related issues with how the "No Validation" status is being used in the Spectrum Identification Results table and how this is shown at the PSM and Spectrum tables.

**Comment by hbarsnes** [comment]
Screenshot indicating some of the issue in the Spectrum IDs tab:

![image](https://user-images.githubusercontent.com/13151214/58879497-1847e900-86d6-11e9-9591-c9630e927088.png)

The two main things to note here: 1) nothing is indicated as validated in the bottom left table, and 2) line 4855 in the upper table is indicated with a confidence of 100% even though there are no matches.

The data used is the standard example dataset.

**Comment by mvaudel** [comment]
Validation status is back with commit. 
https://github.com/compomics/peptide-shaker/commit/dc9996351412db6f6247cd76b160368b7bd3b1d2

**Comment by hbarsnes** [comment]
I can confirm that the validation status is back in the Spectrum Identification Results table, but the issue with having a confidence of 100% in the Spectrum Selection Table even though there are no validated PSMs is still there:

![image](https://user-images.githubusercontent.com/13151214/59145487-eb9d1580-89e4-11e9-8f83-8ee9fad31d8d.png)

The Peptide Spectrum Matches table also looks very odd for this particular example? Perhaps it would be better to leave it empty when there are no validated spectrum identification results?

**Comment by hbarsnes** [comment]
> The Peptide Spectrum Matches table also looks very odd for this particular example? Perhaps it would be better to leave it empty when there are no validated spectrum identification results?

This has now been implemented: https://github.com/compomics/peptide-shaker/commit/ec5d11899809a2305f44093000cfd11330acc18b

**Comment by hbarsnes** [comment]
> having a confidence of 100% in the Spectrum Selection Table even though there are no validated PSMs

Seems to be due to the probability being set to 0.0 for the PSM in question. Not sure how this should be properly handled though?

**Comment by mvaudel** [comment]
I think this is already solved but the error will persist on projects created with the bug. Can you try to create a new project?
![Untitled](https://user-images.githubusercontent.com/11632644/59432242-2a690c00-8de7-11e9-8385-5e46ebae987b.png)

**Comment by hbarsnes** [comment]
Nope, still there. Note that (as far as I can tell) it is only a problem when there are search engine PSMs but none of them have been validated. As in the screenshot above.

**Comment by mvaudel** [comment]
OK! 
![Untitled](https://user-images.githubusercontent.com/11632644/59437078-27731900-8df1-11e9-856e-0c499951cd28.png)
These matches are now displayed as "no validation".
https://github.com/compomics/peptide-shaker/commit/be3e76b1cddd08e53604534e15b3365f0df8837c

**Comment by hbarsnes** [comment]
So there are no longer any rows without an icon in the final column then? As in, we do not separate between "no search engine results for the given spectrum" and "there are search engine results but none of them were validated"?

**Comment by mvaudel** [comment]
The no results have nothing, the no results passed the filters have the 'no validation' icon :)

**Comment by hbarsnes** [comment]
Ok. Sounds good! :)
