### ISSUE TITLE
Sorting in the protein, peptide and psm tables no longer works correctly

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#2]
The sorting in the protein, peptide and psm tables is no longer correct when clicking most column headers.

**Comment by CarlosHorro** [comment]
I've been testing the sorting of all columns in Proteins, Peptides and PSM tables and they all seem to work now...

**Comment by hbarsnes** [comment]
Yup. Seems to work again now. :)
