### ISSUE TITLE
FM indexes are not updated if the parsing rules change

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#26]
There is a bug in the current version of the FM index where the decoys (and maybe other details) are not parsed if the index already exists.

I've tracked it down to line 1078 in FMIndex, i.e. `if (loadFasta)`. If the index already exists `loadFasta` will be `false` which means that the `addDataToIndex` method will not be called.

The following code will then not being executed (line 1348):

```
if (fastaParameters != null && ProteinUtils.isDecoy(accession, fastaParameters)) {
     decoyAccessions.add(accession);
}
```

Which results in `decoyAccessions` being empty, and thus no decoys when processing the data in PeptideShaker and no FDR validation.

**Comment by hbarsnes** [comment]
The actual problem seems to be that the index is not updated if the way the file is parsed is changed. In my case I initially loaded the given FASTA file with "-REVERSED" as the decoy tag, but then figured out that it should be "_REVERSED". Upon reloading the data the old index is used and hence the list of decoys is still empty. If I delete the index (or always recreate it, as was my initial fix), the index is updated and the decoys extracted correctly.

So we need a way of checking not only that the index exists, but that it is still valid.

The same issue would perhaps also occur if the content of the FASTA file has been changed without changing the name of the FASTA file?

We used to do these kinds of tests for the .fasta.cui files, but this feature seems to not have been carried on to the FM index?

**Comment by dominik-kopczynski** [comment]
Added a checksum computation for a fasta file, whenever something is changed in the file, the index will be recomputed and restored.

**Comment by hbarsnes** [comment]
But won't this only solve the issue of the FASTA file content changing but not the issue of the FastaParameters having changed?

For example, as in my case, the index was made with "-REVERSED" as the decoy tag, but when using the FASTA file the decoy tag changed to "_REVERSED".

So I think we'd also have to add a check for if the currently used FastaParameters are the same as the ones used to create the index?
