### ISSUE TITLE
Peptides go missing from protein groups

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#27]
Some peptides go missing from the protein groups. For example, take the peptide ELISNASDALDKIR. As the below screenshot shows the PSM indicates that this peptide maps to five proteins:

![image](https://user-images.githubusercontent.com/13151214/59146665-43da1480-89f1-11e9-8a38-4ec04b15d4f1.png)

But when looking up each of these proteins in the Overview tab none of them list the given peptide. The Find feature however finds a match, but is unable to display it (as this would involve selecting a protein to get to the given peptide). The peptide is also found in the Modifications tab. Hence the peptide has not been removed completely, only from the protein/protein groups.

**Comment by mvaudel** [comment]
The peptide is attached to Q58FF6 on my side:
![Untitled](https://user-images.githubusercontent.com/11632644/59438744-5f2f9000-8df4-11e9-8061-867bd5761a64.png)

**Comment by mvaudel** [comment]
Switching between tabs selects the protein as wanted - looks all good?

**Comment by hbarsnes** [comment]
The peptide may be attached to a protein but not to all the proteins it was attached to before
and not to all the proteins listed in the spectrum ids table, where it is indicated to map to P08238, P14625, Q58FF6 and Q58FF7.

**Comment by mvaudel** [comment]
Issue should be solved and protein inference improved with https://github.com/compomics/peptide-shaker/commit/72a0e15abe5311651951399f76b524e4715f4b28.
