### ISSUE TITLE
Many PTMs are not displayed correctly or not parsed at all

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#3]
There are issues with the mapping of PTMs.

For example n-term PTMs put on the c-term (e.g. the pyrolidone ptms from xtandem). In this particular case the PTMs are there in the peptide object, but not shown due to issue with the PeptideUtils.getTaggedModifiedSequence method.

But in other cases, such as the acetylation of the protein n-term, the PTMs seem to be missing completely.

Finally, there are a lot less PTMs than before. Example: Oxidation of M, before 380 peptides, new: 68 peptides.

**Comment by mvaudel** [comment]
commit d7795c21b915733b0fa754d432638606e584cb9d

Modifications should be displayed again and in number comparable to older versions albeit lower.
