### ISSUE TITLE
IdentiPy

### ISSUE THREAD

**Issue by chrishuges** [compomics/peptide-shaker-2.0-issue-tracker#43]
Hi, 

Really liking the new beta releases! I don't see IdentiPy though (CLI or GUI). Am I just missing it, or has it not been fully integrated yet? Not urgent, just wondering. 

Thanks,
Chris

**Comment by hbarsnes** [comment]
Hi Chris,

Perhaps I forgot to add the name to the list of supported formats. I will look into this next week. But if you try loading an IdentiPy pep.xml file it should work?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Chris,

Did you manage to load IdentiPy results in the end? In other words, can I close this issue? :)

Best regards,
Harald
