### ISSUE TITLE
Cannot reopen saved PeptideShaker projects

### ISSUE THREAD

**Issue by MarcIsak** [compomics/peptide-shaker-2.0-issue-tracker#47]
Hi, 

I tried to save a project as a _*.psdb_ file, but the program froze after a while. I had to go into the Task Manager to force it to shut down. 

Interestingly, there was a _psdb-file_ saved to the specified folder. 
But when I tried to load it into a new PeptideShaker session, I encountered this error. See attached.
![pept_error](https://user-images.githubusercontent.com/47174270/70645394-32deba00-1c45-11ea-8d38-4cf3097784d2.png)

I have attached the error log here as well. 

[PeptideShaker 2.0.0-beta log.txt](https://github.com/compomics/peptide-shaker-2.0-issue-tracker/files/3951802/PeptideShaker.2.0.0-beta.log.txt)

Any ideas what could be wrong here? 

Best,

Marc

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

If the project saving is not completed the psdb file will be corrupt and cannot be opened. All the errors in the log file are related to opening the project, it would be more relevant to see any errors occurring when saving the project. But maybe there weren't any?

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, 

I managed to replicate the issue 4 times in a row. This is the procedure: 

1. Successfully load SearchGUI output into PeptideShaker using only 6 out of 20 logical processors, with 24 GB RAM allocated for the Java VM.
2. Click on the Save project button to create a PSDB file.
3. A progress bar shows up, and it is moving initially. 
4. Task manager shows that PeptideShaker uses > 95% of CPU in intervals (strange as I only use 6 logical processors).
5. PeptideShaker takes up 70% of the memory (32GB RAM total).
6. The progress bar freezes, and so does the software. 
7. Must use the Task Manager to force PeptideShaker to turn off. 
8. A corrupt PSDB file is saved, and it seems to have the same size all the time... 

Any ideas on this? 

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

And there are no errors in the PeptideShaker log file when saving? Only when opening?

Would it be possible for you to share the SearchGUI output you are trying to load and save? Then we could check if the error can be reproduce on our end?

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, 

I could share the SearchGUI output with you. But the file is quite big (~400 MB). I could create a Dropbox folder, and share the file with you in this way if it works for you? Then I would need your preferable mail address. 

Best,

Marc



Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

Sharing via Dropbox should work fine. But please share by sharing a link to the zip file containing all the data and not the Dropbox folder directly, as the latter takes up space on by Dropbox account while the former does not. :)

And please make sure that zip file contains all the files required to load the data in PeptideShaker, i.e. not just the search results but also the fasta and mgf files.

You can send the download link to me at harald.barsnes AT gmail.com.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Just confirming that I'm able to reproduce this issue as well. Happens, for example, if I only load the MS Amanda data, and even if the saving then actually completes. So there is clearly a bug here somewhere. I'll get back to you as soon as I've gotten the required input from the other developers.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Marc,

Just wanted to let you know that we are now working with the developers of the database we use when storing and reopening the PeptideShaker projects. Hopefully they will be able to track down the source of the problem so that we can have a new version out soon where large projects can actually be reopened.

Best regards,
Harald

**Comment by MarcIsak** [comment]
Hi Harald, I am looking forward to try the new beta-release once this issue is fixed. 

Best,

 Marc

**Comment by MarcIsak** [comment]
Hi Harald, 

Long time no see! I would just like to know the status of this issue. As you know, I am looking forward to try another beta-version once this issue is fixed!

Best,

Marc

**Comment by hbarsnes** [comment]
Hi Marc,

I'm afraid we have had to yet again change the backend database. Mainly to fix some other performance issues we recently detected, but this should also solve the issue with reopening saved projects. Hopefully a new beta version will be available for testing soon, but I cannot say when. I will keep you posted.

Best regards,
Harald

**Comment by hbarsnes** [comment]
The issue has been solved and a new beta version will released as soon as possible.
