### ISSUE TITLE
Export data as fractions

### ISSUE THREAD

**Issue by hanne-hox** [compomics/peptide-shaker-2.0-issue-tracker#52]
I suddenly discovered in the new beta-version, that my favorite Expore function: the Fractions-pane has disappeared! Any hopes of getting this back?

Or getting any hints on how to make a new report that provides the samples-wise peptides, spectra and intensities?

**Comment by hbarsnes** [comment]
The fraction tab is still there, but it is only enabled for protein level projects and if you are loading results for more than one mgf file. Or are you saying that both of these are true and it is still not enabled?

**Comment by hanne-hox** [comment]
Both are true, but I can't find the Fractions-selection under Export -> Identity features. 
Protein was selected on the drag-down menu on the top right in the start-menu, and 23 mgf-files were loaded.

**Comment by hbarsnes** [comment]
Ah, I thought you meant the Fractions tab in the main PeptideShaker window.

As for the Fractions export I need to check with @mvaudel. I assume it was removed in the refactoring of the code, but not sure if Marc has plans to re-add it or not. @mvaudel Perhaps you can comment on this?

**Comment by hanne-hox** [comment]
correct, it is the export-function that I _really_ need.

**Comment by hanne-hox** [comment]
Did you have a chance to look into this? Can it be implemented, or are there any choices I can do to make a custom report like this?

I got a data set where I need fraction information to be exported, and ran into an issue similar to earlier reported for the older PS-version (issue #366, https://github.com/compomics/peptide-shaker/issues/366). As many as 363 of the 3371 confidently identified proteins do not have peptide, spectra or intensity data coupled to them in the fractions export. 

As in the former thread this issue should be solved in the new beta - but without the possibility to export data in this way, I cannot get the data to process it further.
