### ISSUE TITLE
Error double insertion

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker-2.0-issue-tracker#53]
Hi I got this error with the new Peptide Shaker 2.0 beta version, perhaps it is also a known error? Thanks for your attention!

<img width="791" alt="Screen Shot 2020-04-12 at 11 01 02 PM" src="https://user-images.githubusercontent.com/22406027/79096321-a7b82280-7d11-11ea-9728-cc458b663863.png">

**Comment by hbarsnes** [comment]
PS: Note that I moved the issue to the PeptideShaker 2.0 issue tracker: https://github.com/compomics/peptide-shaker-2.0-issue-tracker.

**Comment by hbarsnes** [comment]
@CarlaCristinaUranga The Tide issue has now been resolved. I will release a new beta version as soon as I've sorted out some other issues as well.

**Comment by hbarsnes** [comment]
> the program passed the aforementioned hurdle now, but it seems to be getting stuck. Is this because of the large size of the database and .mgf file? My files are all 2 GB each, and I am using a large Uniprot database consisting of all bacteria sequences. I am definitely processing each file individually because of the large size. I am not sure how long would be considered normal for completion of the peptide inference step.

If using big files this step can take some time to complete. The only way to make it go faster is to give PeptideShaker more memory. Please see: https://github.com/compomics/compomics-utilities/wiki/JavaTroubleShooting#memory-issues.

If the process does not complete, please send us the PeptideShaker log file.

**Comment by CarlaCristinaUranga** [comment]
Fantastic! Is there a way to troubleshoot protein inference issues? All of
my files are getting stuck at this stage and not proceeding. How long
should this step take?

Best,
Carla

**Comment by CarlaCristinaUranga** [comment]
HibI am running it with 15 GB of memory already. I will send over the log
file if it doesn't proceed in a couple of hours. Thanks!

**Comment by hbarsnes** [comment]
> How long should this step take?

This highly depends on the size of your spectrum files and the protein sequence database used. And to some extent the search settings.

> I am running it with 15 GB of memory already.

The new beta version should require less memory than the current release. But we have not yet tested this in detail. For the old version we often used 60+ GB of memory when processing large datasets. Note that it is possible to process large datasets with a lot less memory, it just will take longer. I'd recommend letting it run overnight.

**Comment by hbarsnes** [comment]
The issue has been closed given that the initial double insertion error was solved. A new beta version will be released as soon as possible.
