### ISSUE TITLE
Fix sorting of PSMs in the Spectrum IDs tab

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#56]
The assumptions table in the Spectrum IDs tab is currently sorted incorrectly, should be sorted on confidence.

See populateIdResultsTable in eu.isas.peptideshaker.gui.tabpanels.SpectrumIdentificationPanel.

**Comment by mvaudel** [comment]
Fixed in https://github.com/compomics/peptide-shaker/commit/4bc0b1a3ebe56ac8c43550ce35d91681ef733867.
