### ISSUE TITLE
PeptideShaker going into endless loop

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [compomics/peptide-shaker-2.0-issue-tracker#59]
Hi, in a previous communication, it was discovered that PeptideShakerCLI on a large-memory server was going into an endless loop because of a bug in reading mgf files, which were generated via msconvert. I was able to overcome this using PeptideShakerGUI on my computer, but I am now running into the same issue using PeptideShakerGUI. No error is reported, the program simply stalls and does not output anything.

I was wondering how this bug fix is going, and why sometimes PeptideShakerGUI works, but PeptideShakerCLI never works.  The database I am using is a custom generic 1.3 G database, any help is appreciated. Thanks!

**Comment by hbarsnes** [comment]
Hi Carla,

This bug has been fixed, but due to other unrelated issues we have not yet been able to update the beta release. I will let you know as soon as a new beta release is available.

Best regards,
Harald

**Comment by CarlaCristinaUranga** [comment]
Ok. Well now is is evident that PeptideShaker freezes at the "Simplify Protein Groups" stage. Thank you and I am looking forward to the new version.

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new releases that have now been made available. If not, please let us know by opening a new issue here: https://github.com/compomics/peptide-shaker/issues.

**Comment by CarlaCristinaUranga** [comment]
YAY!!! Thank you Harald, how awesome. I am wondering, is it a new beta
version or is this version available in the compomics website? Good to hear
you are OK, I hope things are getting better where you are!

Best wishes,

Carla Uranga

**Comment by hbarsnes** [comment]
Hi Carla,

> I am wondering, is it a new beta version or is this version available in the compomics website?

The new normal releases are available via the standard download links. :)

Best regards,
Harald
