### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by VladimirRoudko** [compomics/peptide-shaker-2.0-issue-tracker#60]
Hello,

I am testing peptide-shaker-2.0.0 and encounter a few issues. The analysis of SearchCLI output did not finish correctly and threw an error after "Importing PSMs" step. Overall STDOUT before the error is the following:

Fri Jul 17 02:28:16 EDT 2020 Parsing 01CPTAC_COprospective_W_PNNL_20170123_B1S1_f01.tide-search.target.txt.
Fri Jul 17 02:28:17 EDT 2020 Loading spectra for 01CPTAC_COprospective_W_PNNL_20170123_B1S1_f01.tide-search.target.txt.
10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Fri Jul 17 02:28:17 EDT 2020 Importing PSMs from 01CPTAC_COprospective_W_PNNL_20170123_B1S1_f01.tide-search.target.txt
Fri Jul 17 02:28:28 EDT 2020 PeptideShaker Processing Canceled.
<CompomicsError>PeptideShaker processing canceled. Please see the PeptideShaker log file: /nfs/scratch/vova/compomics/coad_ucec_tmt/compomics_result/01CPTAC_COprospective_W_PNNL_20170123_B1S1/PeptideShaker-2.0.0-beta/resources/PeptideShaker.log</CompomicsError>

Upon checking the log file there was not record left:

Fri Jul 17 02:28:28 EDT 2020: PeptideShaker version 2.0.0-beta.
Memory given to the Java virtual machine: 42949672960.
Total amount of memory in the Java virtual machine: 2147483648.
Free memory: 2128670592.
Java version: 11.0.7.

Fri Jul 17 02:28:29 EDT 2020: PeptideShaker version 2.0.0-beta.
Memory given to the Java virtual machine: 42949672960.
Total amount of memory in the Java virtual machine: 2147483648.
Free memory: 2126655152.
Java version: 11.0.7.

Overall, the run is performed on Ubuntu, Xmx40G, 15 threads per run.  Is there any suggestion to overcome this error? Also, is it worth testing previous PeptideShaker version(-s)?

Thank you!

**Comment by hbarsnes** [comment]
Hi Vladimir,

Have you checked the content of 01CPTAC_COprospective_W_PNNL_20170123_B1S1_f01.tide-search.target.txt? Are there actually any identifications in there?

And is Tide the only search engine causing issues or do you see similar issues if loading the results from the other search engines as well?

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
Hi Harald,

Thank you for quick response! yes, indeed there are identifications in the *.tide-search.target.txt. Identifications done by other search engines are loaded correctly - no errors posted. The worrisome that *resources/PeptideShaker.log does not post any error messages, so its not unclear what actually goes wrong.

Thank you,
Vladimir

**Comment by VladimirRoudko** [comment]
Just a few updates:

I tested the search without Tide engine (including only X-tandem, OMSSA, MSGF, Myrimatch, Comet, Novor and Directag). This time PeptideShaker was able to load results without errors, but got frozen upon loading *.comet.pep.xml at the 5th fraction (total 12 fractions per sample). It seems either Java goes out of memory or hits some endless loop, without throwing any error messages. Is there any way to go around this issue?

Thank you,
Vladimir

**Comment by VladimirRoudko** [comment]
A few more observations:

I have a MS spectra from sample splitted on 12 fractions (total 12 mgf files). Intial Search+PeptideShaker analysis of all 12 files by 8 search engines (Tide, X-tandem, OMSSA, MSGF, Myrimatch, Comet, Novor and Directag) came up with error at peptideShaker level (see above). 

Tests with 7 search engines excluding Tide get frozen upon import of *.comet.pep.xml at 5th fraction (see above again).

Now I tested 4 randomly picked search engines using same 12 mgf files. PeptideShaker got frozen again at importing *.comet.pep.xml but at 12th (last fraction).

Is there any sort of limit in amount of data handled by the PeptideShaker? I handle ~70Gb RAM to Java - is it too low to process that amount of identifications? Here is the PeptideShaker.log:

Tue Jul 21 14:36:39 EDT 2020: PeptideShaker version 2.0.0-beta.
Memory given to the Java virtual machine: 75161927680.
Total amount of memory in the Java virtual machine: 2147483648.
Free memory: 2126676384.
Java version: 11.0.7.

Thank you,
Vladimir

**Comment by hbarsnes** [comment]
Hi Vladimir,

> Is there any sort of limit in amount of data handled by the PeptideShaker? I handle ~70Gb RAM to Java - is it too low to process that amount of identifications?

No, there should not be. It should simply take longer if everything cannot keep in memory.

We have fixed several database issues after the beta version was released though, so it may be the problem you are seeing is already solved. We'll try to release an updated beta version as soon as everybody is back at the office in August. I will let you know when it's availalble.

Best regards,
Harald

**Comment by VladimirRoudko** [comment]
HI Harald,

Thanks for the suggestions - looking forward to the updated beta version. However, it might not be database issue rather PeptideShakerCLI import problem: everytime I run the pipeline it either freezes or cancels the run at the importing PSM step. Interestingly, irrespective to the search engine used.  Have you ever encounter such issue before?

Thanks,
Vladimir

**Comment by hbarsnes** [comment]
This issue should hopefully be fixed in the new release that has now been made available. If not, please let us know by opening a new issue here: https://github.com/compomics/peptide-shaker/issues.
