### ISSUE TITLE
Creating mzIdentML file fails

### ISSUE THREAD

**Issue by InduKhatri** [compomics/peptide-shaker-2.0-issue-tracker#63]
Hello,

I am trying to generate the mzId file from the psdb project file using the following command

java -cp PeptideShaker-2.0.0.jar eu.isas.peptideshaker.cmd.MzidCLI -in FULLPATH/FILE.psdb -contact_first_name FIRST -contact_last_name LAST -contact_email EMAIL -contact_address NL -organization_name ORG -organization_email EMAIL -organization_address Leiden -output_file FULLPATH/CRC_01_mz.mzid -gzip 0

Following Error is produced.

Wed Nov 11 20:56:09 CET 2020: PeptideShaker version 2.0.0.
Memory given to the Java virtual machine: 4294967296.
Total amount of memory in the Java virtual machine: 268435456.
Free memory: 257444256.
Java version: 11.0.8.
java.lang.NullPointerException
	at eu.isas.peptideshaker.cmd.MzidCLIInputBean.<init>(MzidCLIInputBean.java:139)
	at eu.isas.peptideshaker.cmd.MzidCLI.main(MzidCLI.java:276)

Also, when gzip parameter is not provided with the following command produces the trailing warning and errors.

java -cp PeptideShaker-2.0.0.jar eu.isas.peptideshaker.cmd.MzidCLI -in FULLPATH/FILE.psdb -contact_first_name FIRST -contact_last_name LAST -contact_email EMAIL -contact_address NL -organization_name ORG -organization_email EMAIL -organization_address Leiden -output_file FULLPATH/CRC_01_mz.mzid

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.kryo.unsafe.UnsafeUtil (file:/Users/indukhatri/Downloads/PeptideShaker-2.0.0/lib/kryo-5.0.0-RC9.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.unsafe.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Wed Nov 11 20:57:24 CET 2020 The spectrum file was not found. Please provide its location in the command line parameters.

For clarity, the file is ~300 MB.

**Comment by hbarsnes** [comment]
There was a bug in the parsing of the gzip parameter. This has now been fixed and a new version released.

As for the issue of not finding the spectrum file, PeptideShaker is looking for the spectrum files in three locations: 1) the location(s) provided in the psdb file (i.e. the spectrum file location(s) used when creating the psdb file), 2) in the same folder as the psdb file, and 3) in a separate folder named "data" next to the psdb file. If your spectrum file is in any of these locations it should be located. If this is not the case, please let me know and I'll reopen the issue.

BTW, if you are exporting the mzid file immediately after generating a PeptideShaker project, I would recommend including the MzidCLI options (ignoring the -in option) directly on the PeptideShakerCLI command line as this removes the need to reopen the psdb file just to export the mzid file.

PS: For future bug report please use the standard PeptideShaker issue tracker: https://github.com/compomics/peptide-shaker/issues :)
