### ISSUE TITLE
Move the FASTA file out of the search parameters

### ISSUE THREAD

**Issue by hbarsnes** [compomics/peptide-shaker-2.0-issue-tracker#7]
The FASTA file should be moved out of the search parameter JSON file. The work has started in the SearchGUI main dialog, but the backend has to be updated before further work can be done.

**Comment by hbarsnes** [comment]
Current plan: Move the FastaParameters to the FASTA file index (i.e. the .fasta.cui file).

**Comment by hbarsnes** [comment]
Implemented, but needs more testing.

**Comment by CarlosHorro** [comment]
Testing PeptideShaker on OSX and Linux there seems to be something wrong just when loading the initial information as, after choosing the database, the "Database file" field keeps in red (Fasta file not found) and it's not possible to run the program.
No exception is raised. I have to look into it.

PS: By the way, I was firstly testing SG and it seems to work well, although I think there seems to be a problem when trying to remove a user modification. Where is the best place to write about it?

**Comment by CarlosHorro** [comment]
Well it seems it was simple, fastaFile global variable was not set when choosing the fasta file (a local variable was set instead). I've uploaded the fix (also removing the pre-requirement of having search identification parameters and search parameters stablished to have the fasta file approved).
